CREATE DATABASE IF NOT EXISTS `shop`;
USE
  `shop`;
DROP TABLE IF EXISTS
  `admin`;
CREATE TABLE `admin`(
  `id` TINYINT UNSIGNED AUTO_INCREMENT KEY,
  `username` VARCHAR(20) NOT NULL UNIQUE,
  `password` CHAR(32) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
);
DROP TABLE IF EXISTS
  `cate`;
CREATE TABLE `cate`(
  `id` SMALLINT UNSIGNED AUTO_INCREMENT KEY,
  `cName` VARCHAR(50) UNIQUE
);
DROP TABLE IF EXISTS
  `pro`;
CREATE TABLE `pro`(
  `id` INT UNSIGNED AUTO_INCREMENT KEY,
  `pName` VARCHAR(50) NOT NULL UNIQUE,
  `pSn` VARCHAR(50) NOT NULL,
  `pNum` INT UNSIGNED DEFAULT 1,
  `mPrice` DECIMAL(10, 2) NOT NULL,
  `iPrice` DECIMAL(10, 2) NOT NULL,
  `pDesc` TEXT,
  `pImg` VARCHAR(50) NOT NULL,
  `pubTime` INT UNSIGNED NOT NULL,
  `isShow` TINYINT(1) DEFAULT 1,
  `isHot` TINYINT(1) DEFAULT 0,
  `cId` SMALLINT UNSIGNED NOT NULL
);
DROP TABLE IF EXISTS
  `user`;
CREATE TABLE `user`(
  `id` INT UNSIGNED AUTO_INCREMENT KEY,
  `username` VARCHAR(20) NOT NULL UNIQUE,
  `password` CHAR(32) NOT NULL,
  `sex` ENUM("男", "女", "保密") NOT NULL DEFAULT "保密",
  `face` VARCHAR(50) NOT NULL,
  `regTime` INT UNSIGNED NOT NULL
);
DROP TABLE IF EXISTS
  `album`;
CREATE TABLE `album`(
  `id` INT UNSIGNED AUTO_INCREMENT KEY,
  `pid` INT UNSIGNED NOT NULL,
  `albumPath` VARCHAR(50) NOT NULL
);